/*
  This source orginal from: https://github.com/axiom-data-science/jdbc-named-parameters/
*/

using com.informix.jdbc;
using java.io;
using java.lang;
using java.math;
using java.sql;
using java.util;
using Ormix.retry;

namespace Ormix.NamedParam
{
    public class DelegatingPreparedStatement : PreparedStatement
    {
        private readonly PreparedStatement delegateStatement;
        private RetryExecution queryRetryExecution = new RetryExecution(RetryType.Query);

        protected PreparedStatement getDelegate()
        {
            return delegateStatement;
        }

        public string? SqlQuery => (delegateStatement is IfxStatement ifx) ? ifx?.commandString : null;

        public DelegatingPreparedStatement(PreparedStatement delegateStatement)
        {
            this.delegateStatement = delegateStatement ?? throw new ArgumentNullException(nameof(delegateStatement));
        }

        protected virtual void Dispose(bool disposing)
        {
            // Cleanup resources
            if (delegateStatement != null &&
                !delegateStatement.isClosed())
                delegateStatement?.close();

            if (!this.isClosed())
                this.close();

            delegateStatement?.Dispose();
        }

        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }

        ~DelegatingPreparedStatement()
        {
            Dispose(false);
        }

        public void addBatch()
        {
            queryRetryExecution.Handle(() => delegateStatement.addBatch());
        }

        public void addBatch(string sql)
        {            
            queryRetryExecution.Handle(() => delegateStatement.addBatch(sql));
        }

        public void cancel()
        {
            queryRetryExecution.Handle(() => delegateStatement.cancel());
        }

        public void clearBatch()
        {            
            queryRetryExecution.Handle(() => delegateStatement.clearBatch());
        }

        public void clearParameters()
        {
            queryRetryExecution.Handle(() => delegateStatement.clearParameters());
        }

        public void clearWarnings()
        {
            queryRetryExecution.Handle(() => delegateStatement.clearWarnings());
        }

        public void close()
        {
            queryRetryExecution.Handle(() => delegateStatement.close());
        }

        public void closeOnCompletion()
        {
            queryRetryExecution.Handle(() => delegateStatement.closeOnCompletion());
        }

        public bool execute()
        {
            return queryRetryExecution.Handle<bool>(() => delegateStatement.execute());
        }

        public bool execute(string sql)
        {
            return queryRetryExecution.Handle<bool>(() => delegateStatement.execute(sql));
        }

        public bool execute(string sql, int autoGeneratedKeys)
        {
            return queryRetryExecution.Handle<bool>(() => delegateStatement.execute(sql, autoGeneratedKeys));
        }

        public bool execute(string sql, int[] columnIndexes)
        {
            return queryRetryExecution.Handle<bool>(() => delegateStatement.execute(sql, columnIndexes));
        }

        public bool execute(string sql, string[] columnNames)
        {
            return queryRetryExecution.Handle<bool>(() => delegateStatement.execute(sql, columnNames));
        }

        public int[] executeBatch()
        {
            return queryRetryExecution.Handle<int[]>(() => delegateStatement.executeBatch());
        }

        public long[] executeLargeBatch()
        {
            return queryRetryExecution.Handle<long[]>(() => delegateStatement.executeLargeBatch());
        }

        public long executeLargeUpdate()
        {
            return queryRetryExecution.Handle<long>(() => delegateStatement.executeLargeUpdate());
        }

        public long executeLargeUpdate(string sql)
        {
            return delegateStatement.executeLargeUpdate(sql);
        }

        public long executeLargeUpdate(string sql, int autoGeneratedKeys)
        {
            return delegateStatement.executeLargeUpdate(sql, autoGeneratedKeys);
        }

        public long executeLargeUpdate(string sql, int[] columnIndexes)
        {
            return delegateStatement.executeLargeUpdate(sql, columnIndexes);
        }

        public long executeLargeUpdate(string sql, string[] columnNames)
        {
            return delegateStatement.executeLargeUpdate(sql, columnNames);
        }

        public ResultSet executeQuery()
        {
            return queryRetryExecution.Handle<ResultSet>(() => delegateStatement.executeQuery());
        }

        public ResultSet executeQuery(string sql)
        {
            return queryRetryExecution.Handle<ResultSet>(() => delegateStatement.executeQuery(sql));
        }

        public int executeUpdate()
        {
            return queryRetryExecution.Handle<int>(() => delegateStatement.executeUpdate());
        }

        public int executeUpdate(string sql)
        {
            return queryRetryExecution.Handle<int>(() => delegateStatement.executeUpdate(sql));
        }

        public int executeUpdate(string sql, int autoGeneratedKeys)
        {
            return queryRetryExecution.Handle<int>(() => delegateStatement.executeUpdate(sql, autoGeneratedKeys));
        }

        public int executeUpdate(string sql, int[] columnIndexes)
        {
            return queryRetryExecution.Handle<int>(() => delegateStatement.executeUpdate(sql, columnIndexes));
        }

        public int executeUpdate(string sql, string[] columnNames)
        {
            return queryRetryExecution.Handle<int>(() => delegateStatement.executeUpdate(sql, columnNames));
        }

        public Connection getConnection()
        {
            return delegateStatement.getConnection();
        }

        public int getFetchDirection()
        {
            return delegateStatement.getFetchDirection();
        }

        public int getFetchSize()
        {
            return delegateStatement.getFetchSize();
        }

        public ResultSet getGeneratedKeys()
        {
            return delegateStatement.getGeneratedKeys();
        }

        public long getLargeMaxRows()
        {
            return delegateStatement.getLargeMaxRows();
        }

        public long getLargeUpdateCount()
        {
            return delegateStatement.getLargeUpdateCount();
        }

        public int getMaxFieldSize()
        {
            return delegateStatement.getMaxFieldSize();
        }

        public int getMaxRows()
        {
            return delegateStatement.getMaxRows();
        }

        public ResultSetMetaData getMetaData()
        {
            return delegateStatement.getMetaData();
        }

        public bool getMoreResults()
        {
            return delegateStatement.getMoreResults();
        }

        public bool getMoreResults(int current)
        {
            return delegateStatement.getMoreResults(current);
        }

        public ParameterMetaData getParameterMetaData()
        {
            return delegateStatement.getParameterMetaData();
        }

        public int getQueryTimeout()
        {
            return delegateStatement.getQueryTimeout();
        }

        public ResultSet getResultSet()
        {
            return delegateStatement.getResultSet();
        }

        public int getResultSetConcurrency()
        {
            return delegateStatement.getResultSetConcurrency();
        }

        public int getResultSetHoldability()
        {
            return delegateStatement.getResultSetHoldability();
        }

        public int getResultSetType()
        {
            return delegateStatement.getResultSetType();
        }

        public int getUpdateCount()
        {
            return delegateStatement.getUpdateCount();
        }

        public SQLWarning getWarnings()
        {
            return delegateStatement.getWarnings();
        }

        public bool isClosed()
        {
            return delegateStatement.isClosed();
        }

        public bool isCloseOnCompletion()
        {
            return delegateStatement.isCloseOnCompletion();
        }

        public bool isPoolable()
        {
            return delegateStatement.isPoolable();
        }

        public bool isWrapperFor(Class iface)
        {
            return delegateStatement.isWrapperFor(iface);
        }

        public void setArray(int parameterIndex, java.sql.Array x)
        {
            delegateStatement.setArray(parameterIndex, x);
        }

        public void setAsciiStream(int parameterIndex, InputStream x, int length)
        {
            delegateStatement.setAsciiStream(parameterIndex, x, length);
        }

        public void setAsciiStream(int parameterIndex, InputStream x, long length)
        {
            delegateStatement.setAsciiStream(parameterIndex, x, length);
        }

        public void setAsciiStream(int parameterIndex, InputStream x)
        {
            delegateStatement.setAsciiStream(parameterIndex, x);
        }

        public void setBigDecimal(int parameterIndex, BigDecimal x)
        {
            delegateStatement.setBigDecimal(parameterIndex, x);
        }

        public void setBinaryStream(int parameterIndex, InputStream x, int length)
        {
            delegateStatement.setBinaryStream(parameterIndex, x, length);
        }

        public void setBinaryStream(int parameterIndex, InputStream x, long length)
        {
            delegateStatement.setBinaryStream(parameterIndex, x, length);
        }

        public void setBinaryStream(int parameterIndex, InputStream x)
        {
            delegateStatement.setBinaryStream(parameterIndex, x);
        }

        public void setBlob(int parameterIndex, Blob x)
        {
            delegateStatement.setBlob(parameterIndex, x);
        }

        public void setBlob(int parameterIndex, InputStream inputStream, long length)
        {
            delegateStatement.setBlob(parameterIndex, inputStream, length);
        }

        public void setBlob(int parameterIndex, InputStream inputStream)
        {
            delegateStatement.setBlob(parameterIndex, inputStream);
        }

        public void setBoolean(int parameterIndex, bool x)
        {
            delegateStatement.setBoolean(parameterIndex, x);
        }

        public void setByte(int parameterIndex, byte x)
        {
            delegateStatement.setByte(parameterIndex, x);
        }

        public void setBytes(int parameterIndex, byte[] x)
        {
            delegateStatement.setBytes(parameterIndex, x);
        }

        public void setCharacterStream(int parameterIndex, Reader reader, int length)
        {
            delegateStatement.setCharacterStream(parameterIndex, reader, length);
        }

        public void setCharacterStream(int parameterIndex, Reader reader, long length)
        {
            delegateStatement.setCharacterStream(parameterIndex, reader, length);
        }

        public void setCharacterStream(int parameterIndex, Reader reader)
        {
            delegateStatement.setCharacterStream(parameterIndex, reader);
        }

        public void setClob(int parameterIndex, Clob x)
        {
            delegateStatement.setClob(parameterIndex, x);
        }

        public void setClob(int parameterIndex, Reader reader, long length)
        {
            delegateStatement.setClob(parameterIndex, reader, length);
        }

        public void setClob(int parameterIndex, Reader reader)
        {
            delegateStatement.setClob(parameterIndex, reader);
        }

        public void setCursorName(string name)
        {
            delegateStatement.setCursorName(name);
        }

        public void setDate(int parameterIndex, java.sql.Date x, Calendar cal)
        {
            delegateStatement.setDate(parameterIndex, x, cal);
        }

        public void setDate(int parameterIndex, java.sql.Date x)
        {
            delegateStatement.setDate(parameterIndex, x);
        }

        public void setDouble(int parameterIndex, double x)
        {
            delegateStatement.setDouble(parameterIndex, x);
        }

        public void setEscapeProcessing(bool enable)
        {
            delegateStatement.setEscapeProcessing(enable);
        }

        public void setFetchDirection(int direction)
        {
            delegateStatement.setFetchDirection(direction);
        }

        public void setFetchSize(int rows)
        {
            delegateStatement.setFetchSize(rows);
        }

        public void setFloat(int parameterIndex, float x)
        {
            delegateStatement.setFloat(parameterIndex, x);
        }

        public void setInt(int parameterIndex, int x)
        {
            delegateStatement.setInt(parameterIndex, x);
        }

        public void setLargeMaxRows(long max)
        {
            delegateStatement.setLargeMaxRows(max);
        }

        public void setLong(int parameterIndex, long x)
        {
            delegateStatement.setLong(parameterIndex, x);
        }

        public void setMaxFieldSize(int max)
        {
            delegateStatement.setMaxFieldSize(max);
        }

        public void setMaxRows(int max)
        {
            delegateStatement.setMaxRows(max);
        }

        public void setNCharacterStream(int parameterIndex, Reader value, long length)
        {
            delegateStatement.setNCharacterStream(parameterIndex, value, length);
        }

        public void setNCharacterStream(int parameterIndex, Reader value)
        {
            delegateStatement.setNCharacterStream(parameterIndex, value);
        }

        public void setNClob(int parameterIndex, NClob value)
        {
            delegateStatement.setNClob(parameterIndex, value);
        }

        public void setNClob(int parameterIndex, Reader reader, long length)
        {
            delegateStatement.setNClob(parameterIndex, reader, length);
        }

        public void setNClob(int parameterIndex, Reader reader)
        {
            delegateStatement.setNClob(parameterIndex, reader);
        }

        public void setNString(int parameterIndex, string value)
        {
            delegateStatement.setNString(parameterIndex, value);
        }

        public void setNull(int parameterIndex, int sqlType)
        {
            delegateStatement.setNull(parameterIndex, sqlType);
        }

        public void setNull(int parameterIndex, int sqlType, string typeName)
        {
            delegateStatement.setNull(parameterIndex, sqlType, typeName);
        }

        public void setObject(int parameterIndex, object x, int targetSqlType)
        {
            delegateStatement.setObject(parameterIndex, x, targetSqlType);
        }

        public void setObject(int parameterIndex, object x, int targetSqlType, int scaleOrLength)
        {
            delegateStatement.setObject(parameterIndex, x, targetSqlType, scaleOrLength);
        }

        public void setObject(int parameterIndex, object x)
        {
            delegateStatement.setObject(parameterIndex, x);
        }

        public void setObject(int parameterIndex, object x, SQLType targetSqlType, int scaleOrLength)
        {
            delegateStatement.setObject(parameterIndex, x, targetSqlType, scaleOrLength);
        }

        public void setObject(int parameterIndex, object x, SQLType targetSqlType)
        {
            delegateStatement.setObject(parameterIndex, x, targetSqlType);
        }

        public void setPoolable(bool poolable)
        {
            delegateStatement.setPoolable(poolable);
        }

        public void setQueryTimeout(int seconds)
        {
            delegateStatement.setQueryTimeout(seconds);
        }

        public void setRef(int parameterIndex, Ref x)
        {
            delegateStatement.setRef(parameterIndex, x);
        }

        public void setRowId(int parameterIndex, RowId x)
        {
            delegateStatement.setRowId(parameterIndex, x);
        }

        public void setShort(int parameterIndex, short x)
        {
            delegateStatement.setShort(parameterIndex, x);
        }

        public void setSQLXML(int parameterIndex, SQLXML xmlObject)
        {
            delegateStatement.setSQLXML(parameterIndex, xmlObject);
        }

        public void setString(int parameterIndex, string x)
        {
            delegateStatement.setString(parameterIndex, x);
        }

        public void setTime(int parameterIndex, Time x)
        {
            delegateStatement.setTime(parameterIndex, x);
        }

        public void setTime(int parameterIndex, Time x, Calendar cal)
        {
            delegateStatement.setTime(parameterIndex, x, cal);
        }

        public void setTimestamp(int parameterIndex, Timestamp x)
        {
            delegateStatement.setTimestamp(parameterIndex, x);
        }

        public void setTimestamp(int parameterIndex, Timestamp x, Calendar cal)
        {
            delegateStatement.setTimestamp(parameterIndex, x, cal);
        }

        public void setUnicodeStream(int parameterIndex, InputStream x, int length)
        {
            delegateStatement.setUnicodeStream(parameterIndex, x, length);
        }

        public void setURL(int parameterIndex, java.net.URL x)
        {
            delegateStatement.setURL(parameterIndex, x);
        }

        public object unwrap(Class iface)
        {
            return delegateStatement.unwrap(iface);
        }
    }
}
