using com.informix.jdbc;
using java.io;
using java.lang;
using java.math;
using java.net;
using java.sql;
using java.util;
using Ormix.retry;


namespace Ormix.NamedParam
{
    public class DelegatingCallebleStatement : CallableStatement
    {
        private readonly CallableStatement delegateStatement;
        private RetryExecution queryRetryExecution = new RetryExecution(RetryType.Query);

        protected CallableStatement getDelegate()
        {
            return delegateStatement;
        }

        public string? SqlQuery => (delegateStatement is IfxStatement ifx) ? ifx?.commandString : null;

        public DelegatingCallebleStatement(CallableStatement delegateStatement)
        {
            this.delegateStatement = delegateStatement ?? throw new ArgumentNullException(nameof(delegateStatement));
        }

        protected virtual void Dispose(bool disposing)
        {
            // Cleanup resources
            if (delegateStatement != null &&
                !delegateStatement.isClosed())
                delegateStatement?.close();

            if (!this.isClosed())
                this.close();

            delegateStatement?.Dispose();
        }

        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }

        ~DelegatingCallebleStatement()
        {
            Dispose(false);
        }

        public void addBatch()
        {
            queryRetryExecution.Handle(() => delegateStatement.addBatch());
        }

        public void addBatch(string sql)
        {
            queryRetryExecution.Handle(() => delegateStatement.addBatch(sql));
        }

        public void cancel()
        {
            queryRetryExecution.Handle(() => delegateStatement.cancel());
        }

        public void clearBatch()
        {
            queryRetryExecution.Handle(() => delegateStatement.clearBatch());
        }

        public void clearParameters()
        {
            queryRetryExecution.Handle(() => delegateStatement.clearParameters());
        }

        public void clearWarnings()
        {
            queryRetryExecution.Handle(() => delegateStatement.clearWarnings());
        }

        public void close()
        {
            queryRetryExecution.Handle(() => delegateStatement.close());
        }

        public void closeOnCompletion()
        {
            queryRetryExecution.Handle(() => delegateStatement.closeOnCompletion());
        }

        public bool execute()
        {
            return queryRetryExecution.Handle<bool>(() => delegateStatement.execute());
        }

        public bool execute(string sql)
        {
            return queryRetryExecution.Handle<bool>(() => delegateStatement.execute(sql));
        }

        public bool execute(string sql, int autoGeneratedKeys)
        {
            return queryRetryExecution.Handle<bool>(() => delegateStatement.execute(sql, autoGeneratedKeys));
        }

        public bool execute(string sql, int[] columnIndexes)
        {
            return queryRetryExecution.Handle<bool>(() => delegateStatement.execute(sql, columnIndexes));
        }

        public bool execute(string sql, string[] columnNames)
        {
            return queryRetryExecution.Handle<bool>(() => delegateStatement.execute(sql, columnNames));
        }

        public int[] executeBatch()
        {
            return queryRetryExecution.Handle<int[]>(() => delegateStatement.executeBatch());
        }

        public long[] executeLargeBatch()
        {
            return queryRetryExecution.Handle<long[]>(() => delegateStatement.executeLargeBatch());
        }

        public long executeLargeUpdate()
        {
            return queryRetryExecution.Handle<long>(() => delegateStatement.executeLargeUpdate());
        }

        public long executeLargeUpdate(string sql)
        {
            return queryRetryExecution.Handle<long>(() => delegateStatement.executeLargeUpdate(sql));
        }

        public long executeLargeUpdate(string sql, int autoGeneratedKeys)
        {
            return queryRetryExecution.Handle<long>(() => delegateStatement.executeLargeUpdate(sql, autoGeneratedKeys));
        }

        public long executeLargeUpdate(string sql, int[] columnIndexes)
        {
            return queryRetryExecution.Handle<long>(() => delegateStatement.executeLargeUpdate(sql, columnIndexes));
        }

        public long executeLargeUpdate(string sql, string[] columnNames)
        {
            return queryRetryExecution.Handle<long>(() => delegateStatement.executeLargeUpdate(sql, columnNames));
        }

        public ResultSet executeQuery()
        {
            return queryRetryExecution.Handle<ResultSet>(() => delegateStatement.executeQuery());
        }

        public ResultSet executeQuery(string sql)
        {
            return queryRetryExecution.Handle<ResultSet>(() => delegateStatement.executeQuery(sql));
        }

        public int executeUpdate()
        {
            return queryRetryExecution.Handle<int>(() => delegateStatement.executeUpdate());
        }

        public int executeUpdate(string sql)
        {
            return delegateStatement.executeUpdate(sql);
        }

        public int executeUpdate(string sql, int autoGeneratedKeys)
        {
            return delegateStatement.executeUpdate(sql, autoGeneratedKeys);
        }

        public int executeUpdate(string sql, int[] columnIndexes)
        {
            return queryRetryExecution.Handle<int>(() => delegateStatement.executeUpdate(sql, columnIndexes));
        }

        public int executeUpdate(string sql, string[] columnNames)
        {
            return queryRetryExecution.Handle<int>(() => delegateStatement.executeUpdate(sql, columnNames));
        }

        public java.sql.Array getArray(int parameterIndex)
        {
            return delegateStatement.getArray(parameterIndex);
        }

        public java.sql.Array getArray(string parameterName)
        {
            return delegateStatement.getArray(parameterName);
        }


        [Obsolete]
        public BigDecimal getBigDecimal(int parameterIndex, int scale)
        {
            return delegateStatement.getBigDecimal(parameterIndex, scale);
        }

        public BigDecimal getBigDecimal(int parameterIndex)
        {
            return delegateStatement.getBigDecimal(parameterIndex);
        }

        public BigDecimal getBigDecimal(string parameterName)
        {
            return delegateStatement.getBigDecimal(parameterName);
        }

        public Blob getBlob(int parameterIndex)
        {
            return delegateStatement.getBlob(parameterIndex);
        }

        public Blob getBlob(string parameterName)
        {
            return delegateStatement.getBlob(parameterName);
        }

        public bool getBoolean(int parameterIndex)
        {
            return delegateStatement.getBoolean(parameterIndex);
        }

        public bool getBoolean(string parameterName)
        {
            return delegateStatement.getBoolean(parameterName);
        }

        public byte getByte(int parameterIndex)
        {
            return delegateStatement.getByte(parameterIndex);
        }

        public byte getByte(string parameterName)
        {
            return delegateStatement.getByte(parameterName);
        }

        public byte[] getBytes(int parameterIndex)
        {
            return delegateStatement.getBytes(parameterIndex);
        }

        public byte[] getBytes(string parameterName)
        {
            return delegateStatement.getBytes(parameterName);
        }

        public Reader getCharacterStream(int parameterIndex)
        {
            return delegateStatement.getCharacterStream(parameterIndex);
        }

        public Reader getCharacterStream(string parameterName)
        {
            return delegateStatement.getCharacterStream(parameterName);
        }

        public Clob getClob(int parameterIndex)
        {
            return delegateStatement.getClob(parameterIndex);
        }

        public Clob getClob(string parameterName)
        {
            return delegateStatement.getClob(parameterName);
        }

        public Connection getConnection()
        {
            return delegateStatement.getConnection();
        }

        public java.sql.Date getDate(int parameterIndex)
        {
            return delegateStatement.getDate(parameterIndex);
        }

        public java.sql.Date getDate(int parameterIndex, Calendar cal)
        {
            return delegateStatement.getDate(parameterIndex, cal);
        }

        public java.sql.Date getDate(string parameterName)
        {
            return delegateStatement.getDate(parameterName);
        }

        public java.sql.Date getDate(string parameterName, Calendar cal)
        {
            return delegateStatement.getDate(parameterName, cal);
        }

        public double getDouble(int parameterIndex)
        {
            return delegateStatement.getDouble(parameterIndex);
        }

        public double getDouble(string parameterName)
        {
            return delegateStatement.getDouble(parameterName);
        }

        public int getFetchDirection()
        {
            return delegateStatement.getFetchDirection();
        }

        public int getFetchSize()
        {
            return delegateStatement.getFetchSize();
        }

        public float getFloat(int parameterIndex)
        {
            return delegateStatement.getFloat(parameterIndex);
        }

        public float getFloat(string parameterName)
        {
            return delegateStatement.getFloat(parameterName);
        }

        public ResultSet getGeneratedKeys()
        {
            return delegateStatement.getGeneratedKeys();
        }

        public int getInt(int parameterIndex)
        {
            return delegateStatement.getInt(parameterIndex);
        }

        public int getInt(string parameterName)
        {
            return delegateStatement.getInt(parameterName);
        }

        public long getLargeMaxRows()
        {
            return delegateStatement.getLargeMaxRows();
        }

        public long getLargeUpdateCount()
        {
            return delegateStatement.getLargeUpdateCount();
        }

        public long getLong(int parameterIndex)
        {
            return delegateStatement.getLong(parameterIndex);
        }

        public long getLong(string parameterName)
        {
            return delegateStatement.getLong(parameterName);
        }

        public int getMaxFieldSize()
        {
            return delegateStatement.getMaxFieldSize();
        }

        public int getMaxRows()
        {
            return delegateStatement.getMaxRows();
        }

        public ResultSetMetaData getMetaData()
        {
            return delegateStatement.getMetaData();
        }

        public bool getMoreResults()
        {
            return delegateStatement.getMoreResults();
        }

        public bool getMoreResults(int current)
        {
            return delegateStatement.getMoreResults(current);
        }

        public Reader getNCharacterStream(int parameterIndex)
        {
            return delegateStatement.getNCharacterStream(parameterIndex);
        }

        public Reader getNCharacterStream(string parameterName)
        {
            return delegateStatement.getNCharacterStream(parameterName);
        }

        public NClob getNClob(int parameterIndex)
        {
            return delegateStatement.getNClob(parameterIndex);
        }

        public NClob getNClob(string parameterName)
        {
            return delegateStatement.getNClob(parameterName);
        }

        public string getNString(int parameterIndex)
        {
            return delegateStatement.getNString(parameterIndex);
        }

        public string getNString(string parameterName)
        {
            return delegateStatement.getNString(parameterName);
        }

        public object getObject(int parameterIndex)
        {
            return delegateStatement.getObject(parameterIndex);
        }

        public object getObject(int parameterIndex, Map map)
        {
            return delegateStatement.getObject(parameterIndex, map);
        }

        public object getObject(string parameterName)
        {
            return delegateStatement.getObject(parameterName);
        }

        public object getObject(string parameterName, Map map)
        {
            return delegateStatement.getObject(parameterName, map);
        }

        public object getObject(int parameterIndex, Class type)
        {
            return delegateStatement.getObject(parameterIndex, type);
        }

        public object getObject(string parameterName, Class type)
        {
            return delegateStatement.getObject(parameterName, type);
        }

        public ParameterMetaData getParameterMetaData()
        {
            return delegateStatement.getParameterMetaData();
        }

        public int getQueryTimeout()
        {
            return delegateStatement.getQueryTimeout();
        }

        public Ref getRef(int parameterIndex)
        {
            return delegateStatement.getRef(parameterIndex);
        }

        public Ref getRef(string parameterName)
        {
            return delegateStatement.getRef(parameterName);
        }

        public ResultSet getResultSet()
        {
            return delegateStatement.getResultSet();
        }

        public int getResultSetConcurrency()
        {
            return delegateStatement.getResultSetConcurrency();
        }

        public int getResultSetHoldability()
        {
            return delegateStatement.getResultSetHoldability();
        }

        public int getResultSetType()
        {
            return delegateStatement.getResultSetType();
        }

        public RowId getRowId(int parameterIndex)
        {
            return delegateStatement.getRowId(parameterIndex);
        }

        public RowId getRowId(string parameterName)
        {
            return delegateStatement.getRowId(parameterName);
        }

        public short getShort(int parameterIndex)
        {
            return delegateStatement.getShort(parameterIndex);
        }

        public short getShort(string parameterName)
        {
            return delegateStatement.getShort(parameterName);
        }

        public SQLXML getSQLXML(int parameterIndex)
        {
            return delegateStatement.getSQLXML(parameterIndex);
        }

        public SQLXML getSQLXML(string parameterName)
        {
            return delegateStatement.getSQLXML(parameterName);
        }

        public string getString(int parameterIndex)
        {
            return delegateStatement.getString(parameterIndex);
        }

        public string getString(string parameterName)
        {
            return delegateStatement.getString(parameterName);
        }

        public Time getTime(int parameterIndex)
        {
            return delegateStatement.getTime(parameterIndex);
        }

        public Time getTime(int parameterIndex, Calendar cal)
        {
            return delegateStatement.getTime(parameterIndex, cal);
        }

        public Time getTime(string parameterName)
        {
            return delegateStatement.getTime(parameterName);
        }

        public Time getTime(string parameterName, Calendar cal)
        {
            return delegateStatement.getTime(parameterName, cal);
        }

        public Timestamp getTimestamp(int parameterIndex)
        {
            return delegateStatement.getTimestamp(parameterIndex);
        }

        public Timestamp getTimestamp(int parameterIndex, Calendar cal)
        {
            return delegateStatement.getTimestamp(parameterIndex, cal);
        }

        public Timestamp getTimestamp(string parameterName)
        {
            return delegateStatement.getTimestamp(parameterName);
        }

        public Timestamp getTimestamp(string parameterName, Calendar cal)
        {
            return delegateStatement.getTimestamp(parameterName, cal);
        }

        public int getUpdateCount()
        {
            return delegateStatement.getUpdateCount();
        }

        public URL getURL(int parameterIndex)
        {
            return delegateStatement.getURL(parameterIndex);
        }

        public URL getURL(string parameterName)
        {
            return delegateStatement.getURL(parameterName);
        }

        public SQLWarning getWarnings()
        {
            return delegateStatement.getWarnings();
        }

        public bool isClosed()
        {
            return delegateStatement.isClosed();
        }

        public bool isCloseOnCompletion()
        {
            return delegateStatement.isCloseOnCompletion();
        }

        public bool isPoolable()
        {
            return delegateStatement.isPoolable();
        }

        public bool isWrapperFor(Class iface)
        {
            return delegateStatement.isWrapperFor(iface);
        }

        public void registerOutParameter(int parameterIndex, int sqlType)
        {
            delegateStatement.registerOutParameter(parameterIndex, sqlType);
        }

        public void registerOutParameter(int parameterIndex, int sqlType, int scale)
        {
            delegateStatement.registerOutParameter(parameterIndex, sqlType, scale);
        }

        public void registerOutParameter(int parameterIndex, int sqlType, string typeName)
        {
            delegateStatement.registerOutParameter(parameterIndex, sqlType, typeName);
        }

        public void registerOutParameter(string parameterName, int sqlType)
        {
            delegateStatement.registerOutParameter(parameterName, sqlType);
        }

        public void registerOutParameter(string parameterName, int sqlType, int scale)
        {
            delegateStatement.registerOutParameter(parameterName, sqlType, scale);
        }

        public void registerOutParameter(string parameterName, int sqlType, string typeName)
        {
            delegateStatement.registerOutParameter(parameterName, sqlType, typeName);
        }

        public void registerOutParameter(int parameterIndex, SQLType sqlType)
        {
            delegateStatement.registerOutParameter(parameterIndex, sqlType);
        }

        public void registerOutParameter(int parameterIndex, SQLType sqlType, int scale)
        {
            delegateStatement.registerOutParameter(parameterIndex, sqlType, scale);
        }

        public void registerOutParameter(int parameterIndex, SQLType sqlType, string typeName)
        {
            delegateStatement.registerOutParameter(parameterIndex, sqlType, typeName);
        }

        public void registerOutParameter(string parameterName, SQLType sqlType)
        {
            delegateStatement.registerOutParameter(parameterName, sqlType);
        }

        public void registerOutParameter(string parameterName, SQLType sqlType, int scale)
        {
            delegateStatement.registerOutParameter(parameterName, sqlType, scale);
        }

        public void registerOutParameter(string parameterName, SQLType sqlType, string typeName)
        {
            delegateStatement.registerOutParameter(parameterName, sqlType, typeName);
        }

        public void setArray(int parameterIndex, java.sql.Array x)
        {
            delegateStatement.setArray(parameterIndex, x);
        }

        public void setAsciiStream(string parameterName, InputStream x, int length)
        {
            delegateStatement.setAsciiStream(parameterName, x, length);
        }

        public void setAsciiStream(string parameterName, InputStream x, long length)
        {
            delegateStatement.setAsciiStream(parameterName, x, length);
        }

        public void setAsciiStream(string parameterName, InputStream x)
        {
            delegateStatement.setAsciiStream(parameterName, x);
        }

        public void setAsciiStream(int parameterIndex, InputStream x, int length)
        {
            delegateStatement.setAsciiStream(parameterIndex, x, length);
        }

        public void setAsciiStream(int parameterIndex, InputStream x, long length)
        {
            delegateStatement.setAsciiStream(parameterIndex, x, length);
        }

        public void setAsciiStream(int parameterIndex, InputStream x)
        {
            delegateStatement.setAsciiStream(parameterIndex, x);
        }

        public void setBigDecimal(string parameterName, BigDecimal x)
        {
            delegateStatement.setBigDecimal(parameterName, x);
        }

        public void setBigDecimal(int parameterIndex, BigDecimal x)
        {
            delegateStatement.setBigDecimal(parameterIndex, x);
        }

        public void setBinaryStream(string parameterName, InputStream x, int length)
        {
            delegateStatement.setBinaryStream(parameterName, x, length);
        }

        public void setBinaryStream(string parameterName, InputStream x, long length)
        {
            delegateStatement.setBinaryStream(parameterName, x, length);
        }

        public void setBinaryStream(string parameterName, InputStream x)
        {
            delegateStatement.setBinaryStream(parameterName, x);
        }

        public void setBinaryStream(int parameterIndex, InputStream x, int length)
        {
            delegateStatement.setBinaryStream(parameterIndex, x, length);
        }

        public void setBinaryStream(int parameterIndex, InputStream x, long length)
        {
            delegateStatement.setBinaryStream(parameterIndex, x, length);
        }

        public void setBinaryStream(int parameterIndex, InputStream x)
        {
            delegateStatement.setBinaryStream(parameterIndex, x);
        }

        public void setBlob(string parameterName, InputStream inputStream, long length)
        {
            delegateStatement.setBlob(parameterName, inputStream, length);
        }

        public void setBlob(string parameterName, Blob x)
        {
            delegateStatement.setBlob(parameterName, x);
        }

        public void setBlob(string parameterName, InputStream inputStream)
        {
            delegateStatement.setBlob(parameterName, inputStream);
        }

        public void setBlob(int parameterIndex, Blob x)
        {
            delegateStatement.setBlob(parameterIndex, x);
        }

        public void setBlob(int parameterIndex, InputStream inputStream, long length)
        {
            delegateStatement.setBlob(parameterIndex, inputStream, length);
        }

        public void setBlob(int parameterIndex, InputStream inputStream)
        {
            delegateStatement.setBlob(parameterIndex, inputStream);
        }

        public void setBoolean(string parameterName, bool x)
        {
            delegateStatement.setBoolean(parameterName, x);
        }

        public void setBoolean(int parameterIndex, bool x)
        {
            delegateStatement.setBoolean(parameterIndex, x);
        }

        public void setByte(string parameterName, byte x)
        {
            delegateStatement.setByte(parameterName, x);
        }

        public void setByte(int parameterIndex, byte x)
        {
            delegateStatement.setByte(parameterIndex, x);
        }

        public void setBytes(string parameterName, byte[] x)
        {
            delegateStatement.setBytes(parameterName, x);
        }

        public void setBytes(int parameterIndex, byte[] x)
        {
            delegateStatement.setBytes(parameterIndex, x);
        }

        public void setCharacterStream(string parameterName, Reader reader, int length)
        {
            delegateStatement.setCharacterStream(parameterName, reader, length);
        }

        public void setCharacterStream(string parameterName, Reader reader, long length)
        {
            delegateStatement.setCharacterStream(parameterName, reader, length);
        }

        public void setCharacterStream(string parameterName, Reader reader)
        {
            delegateStatement.setCharacterStream(parameterName, reader);
        }

        public void setCharacterStream(int parameterIndex, Reader reader, int length)
        {
            delegateStatement.setCharacterStream(parameterIndex, reader, length);
        }

        public void setCharacterStream(int parameterIndex, Reader reader, long length)
        {
            delegateStatement.setCharacterStream(parameterIndex, reader, length);
        }

        public void setCharacterStream(int parameterIndex, Reader reader)
        {
            delegateStatement.setCharacterStream(parameterIndex, reader);
        }

        public void setClob(string parameterName, Reader reader, long length)
        {
            delegateStatement.setClob(parameterName, reader, length);
        }

        public void setClob(string parameterName, Clob x)
        {
            delegateStatement.setClob(parameterName, x);
        }

        public void setClob(string parameterName, Reader reader)
        {
            delegateStatement.setClob(parameterName, reader);
        }

        public void setClob(int parameterIndex, Clob x)
        {
            delegateStatement.setClob(parameterIndex, x);
        }

        public void setClob(int parameterIndex, Reader reader, long length)
        {
            delegateStatement.setClob(parameterIndex, reader, length);
        }

        public void setClob(int parameterIndex, Reader reader)
        {
            delegateStatement.setClob(parameterIndex, reader);
        }

        public void setCursorName(string name)
        {
            delegateStatement.setCursorName(name);
        }

        public void setDate(string parameterName, java.sql.Date x)
        {
            delegateStatement.setDate(parameterName, x);
        }

        public void setDate(string parameterName, java.sql.Date x, Calendar cal)
        {
            delegateStatement.setDate(parameterName, x, cal);
        }

        public void setDate(int parameterIndex, java.sql.Date x, Calendar cal)
        {
            delegateStatement.setDate(parameterIndex, x, cal);
        }

        public void setDate(int parameterIndex, java.sql.Date x)
        {
            delegateStatement.setDate(parameterIndex, x);
        }

        public void setDouble(string parameterName, double x)
        {
            delegateStatement.setDouble(parameterName, x);
        }

        public void setDouble(int parameterIndex, double x)
        {
            delegateStatement.setDouble(parameterIndex, x);
        }

        public void setEscapeProcessing(bool enable)
        {
            delegateStatement.setEscapeProcessing(enable);
        }

        public void setFetchDirection(int direction)
        {
            delegateStatement.setFetchDirection(direction);
        }

        public void setFetchSize(int rows)
        {
            delegateStatement.setFetchSize(rows);
        }

        public void setFloat(string parameterName, float x)
        {
            delegateStatement.setFloat(parameterName, x);
        }

        public void setFloat(int parameterIndex, float x)
        {
            delegateStatement.setFloat(parameterIndex, x);
        }

        public void setInt(string parameterName, int x)
        {
            delegateStatement.setInt(parameterName, x);
        }

        public void setInt(int parameterIndex, int x)
        {
            delegateStatement.setInt(parameterIndex, x);
        }

        public void setLargeMaxRows(long max)
        {
            delegateStatement.setLargeMaxRows(max);
        }

        public void setLong(string parameterName, long x)
        {
            delegateStatement.setLong(parameterName, x);
        }

        public void setLong(int parameterIndex, long x)
        {
            delegateStatement.setLong(parameterIndex, x);
        }

        public void setMaxFieldSize(int max)
        {
            delegateStatement.setMaxFieldSize(max);
        }

        public void setMaxRows(int max)
        {
            delegateStatement.setMaxRows(max);
        }

        public void setNCharacterStream(string parameterName, Reader value, long length)
        {
            delegateStatement.setNCharacterStream(parameterName, value, length);
        }

        public void setNCharacterStream(string parameterName, Reader value)
        {
            delegateStatement.setNCharacterStream(parameterName, value);
        }

        public void setNCharacterStream(int parameterIndex, Reader value, long length)
        {
            delegateStatement.setNCharacterStream(parameterIndex, value, length);
        }

        public void setNCharacterStream(int parameterIndex, Reader value)
        {
            delegateStatement.setNCharacterStream(parameterIndex, value);
        }

        public void setNClob(string parameterName, NClob value)
        {
            delegateStatement.setNClob(parameterName, value);
        }

        public void setNClob(string parameterName, Reader reader, long length)
        {
            delegateStatement.setNClob(parameterName, reader, length);
        }

        public void setNClob(string parameterName, Reader reader)
        {
            delegateStatement.setNClob(parameterName, reader);
        }

        public void setNClob(int parameterIndex, NClob value)
        {
            delegateStatement.setNClob(parameterIndex, value);
        }

        public void setNClob(int parameterIndex, Reader reader, long length)
        {
            delegateStatement.setNClob(parameterIndex, reader, length);
        }

        public void setNClob(int parameterIndex, Reader reader)
        {
            delegateStatement.setNClob(parameterIndex, reader);
        }

        public void setNString(string parameterName, string value)
        {
            delegateStatement.setNString(parameterName, value);
        }

        public void setNString(int parameterIndex, string value)
        {
            delegateStatement.setNString(parameterIndex, value);
        }

        public void setNull(string parameterName, int sqlType)
        {
            delegateStatement.setNull(parameterName, sqlType);
        }

        public void setNull(string parameterName, int sqlType, string typeName)
        {
            delegateStatement.setNull(parameterName, sqlType, typeName);
        }

        public void setNull(int parameterIndex, int sqlType)
        {
            delegateStatement.setNull(parameterIndex, sqlType);
        }

        public void setNull(int parameterIndex, int sqlType, string typeName)
        {
            delegateStatement.setNull(parameterIndex, sqlType, typeName);
        }

        public void setObject(string parameterName, object x, int targetSqlType, int scale)
        {
            delegateStatement.setObject(parameterName, x, targetSqlType, scale);
        }

        public void setObject(string parameterName, object x, int targetSqlType)
        {
            delegateStatement.setObject(parameterName, x, targetSqlType);
        }

        public void setObject(string parameterName, object x)
        {
            delegateStatement.setObject(parameterName, x);
        }

        public void setObject(string parameterName, object x, SQLType targetSqlType, int scaleOrLength)
        {
            delegateStatement.setObject(parameterName, x, targetSqlType, scaleOrLength);
        }

        public void setObject(string parameterName, object x, SQLType targetSqlType)
        {
            delegateStatement.setObject(parameterName, x, targetSqlType);
        }

        public void setObject(int parameterIndex, object x, int targetSqlType)
        {
            delegateStatement.setObject(parameterIndex, x, targetSqlType);
        }

        public void setObject(int parameterIndex, object x, int targetSqlType, int scaleOrLength)
        {
            delegateStatement.setObject(parameterIndex, x, targetSqlType, scaleOrLength);
        }

        public void setObject(int parameterIndex, object x)
        {
            delegateStatement.setObject(parameterIndex, x);
        }

        public void setObject(int parameterIndex, object x, SQLType targetSqlType, int scaleOrLength)
        {
            delegateStatement.setObject(parameterIndex, x, targetSqlType, scaleOrLength);
        }

        public void setObject(int parameterIndex, object x, SQLType targetSqlType)
        {
            delegateStatement.setObject(parameterIndex, x, targetSqlType);
        }

        public void setPoolable(bool poolable)
        {
            delegateStatement.setPoolable(poolable);
        }

        public void setQueryTimeout(int seconds)
        {
            delegateStatement.setQueryTimeout(seconds);
        }

        public void setRef(int parameterIndex, Ref x)
        {
            delegateStatement.setRef(parameterIndex, x);
        }

        public void setRowId(string parameterName, RowId x)
        {
            delegateStatement.setRowId(parameterName, x);
        }

        public void setRowId(int parameterIndex, RowId x)
        {
            delegateStatement.setRowId(parameterIndex, x);
        }

        public void setShort(string parameterName, short x)
        {
            delegateStatement.setShort(parameterName, x);
        }

        public void setShort(int parameterIndex, short x)
        {
            delegateStatement.setShort(parameterIndex, x);
        }

        public void setSQLXML(string parameterName, SQLXML xmlObject)
        {
            delegateStatement.setSQLXML(parameterName, xmlObject);
        }

        public void setSQLXML(int parameterIndex, SQLXML xmlObject)
        {
            delegateStatement.setSQLXML(parameterIndex, xmlObject);
        }

        public void setString(string parameterName, string x)
        {
            delegateStatement.setString(parameterName, x);
        }

        public void setString(int parameterIndex, string x)
        {
            delegateStatement.setString(parameterIndex, x);
        }

        public void setTime(string parameterName, Time x)
        {
            delegateStatement.setTime(parameterName, x);
        }

        public void setTime(string parameterName, Time x, Calendar cal)
        {
            delegateStatement.setTime(parameterName, x, cal);
        }

        public void setTime(int parameterIndex, Time x)
        {
            delegateStatement.setTime(parameterIndex, x);
        }

        public void setTime(int parameterIndex, Time x, Calendar cal)
        {
            delegateStatement.setTime(parameterIndex, x, cal);
        }

        public void setTimestamp(string parameterName, Timestamp x)
        {
            delegateStatement.setTimestamp(parameterName, x);
        }

        public void setTimestamp(string parameterName, Timestamp x, Calendar cal)
        {
            delegateStatement.setTimestamp(parameterName, x, cal);
        }

        public void setTimestamp(int parameterIndex, Timestamp x)
        {
            delegateStatement.setTimestamp(parameterIndex, x);
        }

        public void setTimestamp(int parameterIndex, Timestamp x, Calendar cal)
        {
            delegateStatement.setTimestamp(parameterIndex, x, cal);
        }


        [Obsolete]
        public void setUnicodeStream(int parameterIndex, InputStream x, int length)
        {
            delegateStatement.setUnicodeStream(parameterIndex, x, length);
        }

        public void setURL(string parameterName, URL val)
        {
            delegateStatement.setURL(parameterName, val);
        }

        public void setURL(int parameterIndex, URL x)
        {
            delegateStatement.setURL(parameterIndex, x);
        }

        public object unwrap(Class iface)
        {
            return delegateStatement.unwrap(iface);
        }

        public bool wasNull()
        {
            return delegateStatement.wasNull();
        }
    }
}
